name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, aarch64]
        include:
          - os: ubuntu-latest
            arch: x64
            container: ubuntu:22.04
          - os: ubuntu-latest
            arch: aarch64
            container: arm64v8/ubuntu:22.04
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: aarch64
            container: mcr.microsoft.com/windows/servercore:ltsc2019

    runs-on: ${{ matrix.os }}

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup C++
        uses: actions/setup-cpp@v2
        with:
          architecture: ${{ matrix.arch }}
          cmake-version: '3.27'

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libjson-c-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install curl
          Invoke-WebRequest "https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp" -OutFile "path/to/your/include/dir/json.hpp"

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install curl
          brew install nlohmann-json

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ./build/test
