name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            container: ubuntu:22.04
          - architecture: aarch64
            container: arm64v8/ubuntu:22.04

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          apt update
          apt full-upgrade -y
          apt auto-remove -y
          apt install -y build-essential g++ make cmake pkg-config git wget curl zip unzip tar

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg
          /opt/vcpkg/bootstrap-vcpkg.sh
          ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg

      - name: Clone project repository
        run: |
          git clone https://github.com/lk-libs/libcpp-http-client.git /root/libcpp-http-client

      - name: Run cmake with vcpkg toolchain
        run: |
          cd /root/libcpp-http-client
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build the project
        run: |
          cd /root/libcpp-http-client
          cmake --build build --config Release

      - name: Run tests
        run: |
          cd /root/libcpp-http-client
          ./build/test/test
