name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout vcpkg
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vcpkg'
          path: 'vcpkg'

      - name: Install vcpkg dependencies
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install curl jsoncpp nlohmann-json

      - name: Configure CMake with vcpkg toolchain
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Test
        run: |
          ./build/test
