name: windows-x86_64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install git
          choco install ninja

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          .\C:\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=C:\vcpkg" | Out-File -Append -Encoding ascii $env:GITHUB_ENV

      - name: Integrate vcpkg and install dependencies
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          .\C:\vcpkg\vcpkg integrate install
          .\C:\vcpkg\vcpkg install --triplet x64-windows your-library-list

      - name: Prepare build environment
        run: |
          echo "CMAKE_TOOLCHAIN_FILE=${env:VCPKG_ROOT}\scripts\buildsystems\vcpkg.cmake" | Out-File -Append -Encoding ascii $env:GITHUB_ENV

      - name: Configure CMake project
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${env:CMAKE_TOOLCHAIN_FILE}

      - name: Build the project
        run: |
          cmake --build build --config Release

      - name: Run tests
        run: |
          .\build\test\YourTestExecutable.exe
